version:  '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/docker/mysql
    working_dir: /mysql
